### ISSUE TITLE
coins.txt in data does not match the file on the page

### ISSUE THREAD

**Issue by Photon9** [pmitev/to-awk-or-not#4]
```   gold     0.1  1986  PRC                 Panda```

rather than the page's 

```   gold     0.1  1986  PRC                 Panda - silver lined```

A fun little bug to start

**Comment by pmitev** [comment]
Thanks for pointing it out. 
There might be more discrepancies, since these files are remnants from the time when the workshop material was hosted on google pages... Perhaps it is time to tidy up a bit the repository ;-)
